name: Rancher Documentation
description: Documentation for Rancher


# Changing these will require updates to Dockerfile
URL: http://rancher.github.io
baseurl: ""

exclude: []

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty

gems:
  - jekyll-redirect-from
